import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Recap | Family Services',
  description: 'Generated by create next app',
};

const Recap = () => {
  return (
    <div>
      <p className="">Recap</p>
    </div>
  );
};

export default Recap;
